var admin = require("firebase-admin");
const { getFirestore, Timestamp } = require("firebase-admin/firestore");

var serviceAccount = require("./serviceAccountKey.json");

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
});

var db = getFirestore();



const moviesData = [
  {
    title: "The Grudge",
    startDate: "2024-12-01",
    endDate: "2024-12-31",
    languages: ["English", "Thai"],
    cast: [
      "Andrea Riseborough",
      "Demián Bichir",
      "John Cho",
      "Betty Gilpin",
      "Lin Shaye",
      "Jacki Weaver",
    ],
    genres: ["Horror", "Supernatural"],
    extract:
      "The Grudge is a 2020 American psychological supernatural horror film written and directed by Nicolas Pesce. Originally announced as a reboot of the 2004 American remake and the original 2002 Japanese horror film Ju-On: The Grudge, the film ended up taking place before and during the events of the 2004 film and its two direct sequels, and is the fourth installment in the American The Grudge film series. The film stars Andrea Riseborough, Demián Bichir, John Cho, Betty Gilpin, Lin Shaye, and Jacki Weaver, and follows a police officer who investigates several murders that are seemingly connected to a single house.",
    thumbnail:
      "https://upload.wikimedia.org/wikipedia/en/3/34/The_Grudge_2020_Poster.jpeg",
  },
  {
    title: "Underwater",
    startDate: "2024-12-01",
    endDate: "2024-12-31",
    languages: ["English", "Thai"],
    cast: [
      "Kristen Stewart",
      "Vincent Cassel",
      "Jessica Henwick",
      "John Gallagher Jr.",
      "Mamoudou Athie",
      "T.J. Miller",
    ],
    genres: ["Action", "Horror", "Science Fiction"],
    extract:
      "Underwater is a 2020 American science fiction action horror film directed by William Eubank. The film stars Kristen Stewart, Vincent Cassel, Jessica Henwick, John Gallagher Jr., Mamoudou Athie, and T.J. Miller.",
    thumbnail:
      "https://upload.wikimedia.org/wikipedia/en/4/4a/Underwater_poster.jpeg",
  },
  {
    title: "Like a Boss",
    startDate: "2024-12-01",
    endDate: "2024-12-31",
    languages: ["English", "Thai"],
    cast: [
      "Tiffany Haddish",
      "Rose Byrne",
      "Salma Hayek",
      "Jennifer Coolidge",
      "Billy Porter",
    ],
    genres: ["Comedy"],
    extract:
      "Like a Boss is a 2020 American comedy film directed by Miguel Arteta, written by Sam Pitman and Adam Cole-Kelly, and starring Tiffany Haddish, Rose Byrne, and Salma Hayek. The plot follows two friends who attempt to take back control of their cosmetics company from an industry titan.",
    thumbnail:
      "https://upload.wikimedia.org/wikipedia/en/9/9a/LikeaBossPoster.jpg",
  },
  {
    title: "Three Christs",
    startDate: "2024-12-01",
    endDate: "2024-12-15",
    languages: ["English", "Thai"],
    cast: [
      "Richard Gere",
      "Peter Dinklage",
      "Walton Goggins",
      "Bradley Whitford",
    ],
    genres: ["Drama"],
    extract:
      "Three Christs, also known as State of Mind, is a 2017 American drama film directed, co-produced, and co-written by Jon Avnet and based on Milton Rokeach's nonfiction book The Three Christs of Ypsilanti. It screened in the Gala Presentations section at the 2017 Toronto International Film Festival. The film is also known as: Three Christs of Ypsilanti, The Three Christs of Ypsilanti, Three Christs of Santa Monica, and The Three Christs of Santa Monica.",
    thumbnail:
      "https://upload.wikimedia.org/wikipedia/en/a/a1/Three_Christs_poster.jpg",
  },
  {
    title: "Inherit the Viper",
    startDate: "2024-12-01",
    endDate: "2024-12-15",
    languages: ["English", "Thai"],
    cast: [
      "Josh Hartnett",
      "Margarita Levieva",
      "Chandler Riggs",
      "Bruce Dern",
      "Owen Teague",
    ],
    genres: ["Crime", "Drama"],
    extract:
      "Inherit the Viper is a 2019 American crime drama film directed by Anthony Jerjen, in his feature directorial debut, from a screenplay by Andrew Crabtree. It stars Josh Hartnett, Margarita Levieva, Chandler Riggs, Bruce Dern, Valorie Curry, Owen Teague, and Dash Mihok.",
    thumbnail:
      "https://upload.wikimedia.org/wikipedia/en/1/1c/Inherit_the_Viper_%282019%29_Film_Poster.jpg",
  },
  {
    title: "The Sonata",
    startDate: "2024-12-01",
    endDate: "2024-12-15",
    languages: ["English", "Thai"],
    cast: ["Freya Tingley", "Simon Abkarian", "Rutger Hauer", "James Faulkner"],
    genres: ["Mystery", "Thriller"],
    extract:
      "The Sonata is a 2018 mystery thriller film, directed by Andrew Desmond, from a screenplay by Desmond and Arthur Morin. It stars Freya Tingley, Simon Abkarian, James Faulkner, Rutger Hauer, Matt Barber and James Kermack. It was released in the United States on January 10, 2020, by Screen Media Films. It grossed $146,595 at the box office and received mixed reviews from critics.",
    thumbnail:
      "https://upload.wikimedia.org/wikipedia/en/1/13/The_Sonata_%282018%29_Film_Poster.jpg",
  },
  {
    title: "The Murder of Nicole Brown Simpson",
    startDate: "2024-12-16",
    endDate: "2024-12-31",
    languages: ["English", "Thai"],
    cast: ["Mena Suvari", "Nick Stahl", "Taryn Manning"],
    genres: ["Crime", "Horror"],
    extract:
      "The Murder of Nicole Brown Simpson is a 2019 American crime horror film directed by Daniel Farrands. The film is loosely based on the murder of Nicole Brown Simpson, presenting a version of events in which Brown Simpson is murdered by serial killer Glen Edward Rogers, and not by O. J. Simpson, her ex-husband and the primary suspect in the case. Though Mena Suvari's performance as Nicole Brown was praised, the film was panned by critics.",
    thumbnail:
      "https://upload.wikimedia.org/wikipedia/en/e/ed/The_Murder_of_Nicole_Brown_Simpson_poster.jpg",
  },
  {
    title: "Bad Boys for Life",
    startDate: "2024-12-16",
    endDate: "2024-12-31",
    languages: ["English", "Thai"],
    cast: [
      "Will Smith",
      "Martin Lawrence",
      "Vanessa Hudgens",
      "Alexander Ludwig",
      "Charles Melton",
      "Paola Núñez",
      "Kate del Castillo",
      "Nicky Jam",
      "Joe Pantoliano",
    ],
    genres: ["Action", "Comedy"],
    extract:
      "Bad Boys for Life is a 2020 American buddy cop action comedy film directed by Adil & Bilall. It is the sequel to Bad Boys II (2003) and the third installment in the Bad Boys franchise. Will Smith, Martin Lawrence, Joe Pantoliano and Theresa Randle reprise their roles in the film and are joined by Paola Núñez, Vanessa Hudgens, Jacob Scipio, Alexander Ludwig, Charles Melton, Kate del Castillo and Nicky Jam. The film was produced by Smith, Jerry Bruckheimer, and Doug Belgrad, with a screenplay written by Chris Bremner, Peter Craig and Joe Carnahan. In Bad Boys for Life, Miami detectives Mike Lowrey and Marcus Burnett investigate a string of murders tied to Lowrey's troubled past.",
    thumbnail:
      "https://upload.wikimedia.org/wikipedia/en/9/90/Bad_Boys_for_Life_poster.jpg",
  },
  {
    title: "Dolittle",
    startDate: "2025-01-01",
    endDate: "2025-01-30",
    languages: ["English", "Thai"],
    cast: [
      "Robert Downey Jr.",
      "Antonio Banderas",
      "Michael Sheen",
      "Emma Thompson",
      "Rami Malek",
      "John Cena",
      "Kumail Nanjiani",
      "Octavia Spencer",
      "Tom Holland",
      "Craig Robinson",
      "Ralph Fiennes",
      "Selena Gomez",
      "Marion Cotillard",
    ],
    genres: ["Adventure", "Fantasy"],
    extract:
      "Dolittle is a 2020 American fantasy adventure film directed by Stephen Gaghan from a screenplay by Gaghan, Dan Gregor, and Doug Mand, based on a story by Thomas Shepherd. Dolittle is based on the title character created by Hugh Lofting and is primarily inspired by the author's second Doctor Dolittle book, The Voyages of Doctor Dolittle (1922). Robert Downey Jr. stars as the title character, alongside Antonio Banderas and Michael Sheen in live-action roles, with Emma Thompson, Rami Malek, John Cena, Kumail Nanjiani, Octavia Spencer, Tom Holland, Craig Robinson, Ralph Fiennes, Selena Gomez, and Marion Cotillard voicing an array of creatures.",
    thumbnail:
      "https://upload.wikimedia.org/wikipedia/en/1/1f/Dolittle_%282020_film_poster%29.png",
  },
  {
    title: "A Fall from Grace",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    languages: ["English", "Thai"],
    cast: [
      "Crystal R. Fox",
      "Phylicia Rashad",
      "Bresha Webb",
      "Mehcad Brooks",
      "Cicely Tyson",
      "Tyler Perry",
    ],
    genres: ["Thriller"],
    extract:
      "A Fall from Grace is a 2020 American thriller film produced, written, and directed by Tyler Perry and his first to be released by Netflix. The film follows a woman who finds a dangerous new love and the novice attorney who defends her in a sensational court case. This was the final film of actor Cicely Tyson before her death in January 2021.",
    thumbnail:
      "https://upload.wikimedia.org/wikipedia/en/4/4e/AFallFromGrace.png",
  },
  {
    title: "The Gentlemen",
    startDate: "2025-12-01",
    endDate: "2025-12-15",
    languages: ["English", "Thai"],
    cast: [
      "Matthew McConaughey",
      "Charlie Hunnam",
      "Henry Golding",
      "Michelle Dockery",
      "Jeremy Strong",
      "Eddie Marsan",
      "Colin Farrell",
      "Hugh Grant",
    ],
    genres: ["Action", "Comedy"],
    extract:
      "The Gentlemen is a 2019 action comedy film written, directed and produced by Guy Ritchie, who developed the story along with Ivan Atkinson and Marn Davies. The film stars Matthew McConaughey, Charlie Hunnam, Henry Golding, Michelle Dockery, Jeremy Strong, Eddie Marsan, Colin Farrell, and Hugh Grant. It follows an American cannabis wholesaler in England who is looking to sell his business, setting off a chain of blackmail and schemes to undermine him.",
    thumbnail:
      "https://upload.wikimedia.org/wikipedia/en/0/06/The_Gentlemen_poster.jpg",
  },
  {
    title: "The Turning",
    startDate: "2024-12-01",
    endDate: "2024-12-15",
    languages: ["English", "Thai"],
    cast: [
      "Mackenzie Davis",
      "Finn Wolfhard",
      "Brooklynn Prince",
      "Joely Richardson",
    ],
    genres: ["Horror", "Supernatural"],
    extract:
      "The Turning is a 2020 American gothic supernatural horror film directed by Floria Sigismondi and written by Carey W. Hayes and Chad Hayes. It is a modern adaptation of the 1898 ghost story The Turn of the Screw by Henry James. It stars Mackenzie Davis, Finn Wolfhard, Brooklynn Prince, and Joely Richardson, and follows a young governess in 1994 who is hired to watch over two children after their parents are killed.",
    thumbnail:
      "https://upload.wikimedia.org/wikipedia/en/a/a2/The_Turning_poster_2020.jpg",
  },
  {
    title: "The Last Full Measure",
    startDate: "2024-12-16",
    endDate: "2024-12-31",
    languages: ["English", "Thai"],
    cast: [
      "Sebastian Stan",
      "Christopher Plummer",
      "William Hurt",
      "Ed Harris",
      "Samuel L. Jackson",
      "Peter Fonda",
      "LisaGay Hamilton",
      "Jeremy Irvine",
      "Diane Ladd",
      "Amy Madigan",
      "John Savage",
      "Bradley Whitford",
    ],
    genres: ["Drama", "War"],
    extract:
      "The Last Full Measure is a 2019 American war drama film written and directed by Todd Robinson. It follows the efforts of fictional Pentagon staffer Scott Huffman and many veterans to see the Medal of Honor awarded to William H. Pitsenbarger, a United States Air Force Pararescueman who flew in helicopter rescue missions during the Vietnam War to aid downed soldiers and pilots. Based on true events, the film stars Sebastian Stan, Christopher Plummer, William Hurt, Ed Harris, Samuel L. Jackson, Jeremy Irvine, and Peter Fonda. It was the final film appearance of Fonda, who died before the film’s release; and Plummer's final on screen appearance before his death in 2021, though it had filmed prior to Knives Out which was released before it.",
    thumbnail:
      "https://upload.wikimedia.org/wikipedia/en/9/9d/The_Last_Full_Measure_2019_poster.jpg",
  },
  {
    title: "John Henry",
    startDate: "2024-12-16",
    endDate: "2024-12-31",
    languages: ["English", "Thai"],
    cast: [
      "Terry Crews",
      "Ludacris",
      "Jamila Velazquez",
      "Ken Foree",
      "Tyler Alvarez",
      "Joseph Julian Soria",
    ],
    genres: ["Drama", "Thriller"],
    extract:
      "John Henry is a 2020 American thriller drama film starring Terry Crews and Ludacris, and directed by Will Forbes. Inspired by the folk lore of John Henry, the plot follows an ex-gang member from Los Angeles who must help two immigrant children who are on the run from his former crime boss. The film had a limited release on January 24, 2020, and received negative reviews from critics.",
    thumbnail:
      "https://upload.wikimedia.org/wikipedia/en/b/b8/JohnHenryPoster.jpeg",
  },
  {
    title: "The Rhythm Section",
    startDate: "2024-12-01",
    endDate: "2024-12-31",
    languages: ["English", "Thai"],
    cast: ["Blake Lively", "Jude Law", "Sterling K. Brown"],
    genres: ["Action", "Thriller"],
    extract:
      "The Rhythm Section is a 2020 action thriller film directed by Reed Morano and with a screenplay by Mark Burnell based on his novel of the same name. Starring Blake Lively, Jude Law and Sterling K. Brown, and follows a grieving woman who seeks revenge after discovering that the plane crash that killed her family was a terrorist attack.",
    thumbnail:
      "https://upload.wikimedia.org/wikipedia/en/9/98/The_Rhythm_Section_poster.jpg",
  },
];

const theatersData = [
  {
    theaterName: "Major Cineplex Ratchayothin",
    location: {
      address: "1839 Phahonyothin Rd, Chatuchak",
      city: "Bangkok",
      country: "Thailand",
      zipcode: "10900",
    },
    movieTitle: [
      "The Grudge",
      "The Gentlemen",
      "Like a Boss",
      "Three Christs",
      "Inherit the Viper",
      "The Murder of Nicole Brown Simpson",
      "Bad Boys for Life",
      "Dolittle",
      "A Fall from Grace",
      "The Sonata",
    ],
    movies: [
      {
        movieTitle: "The Grudge",
        hall: "Hall A",
        time: ["12:00:00", "15:00:00"],
        language: "English",
      },
      {
        movieTitle: "The Gentlemen",
        hall: "Hall B",
        time: ["12:00:00", "15:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "Like a Boss",
        hall: "Hall C",
        time: ["12:00:00", "15:00:00"],
        language: "English",
      },
      {
        movieTitle: "Three Christs",
        hall: "Hall D",
        time: ["12:00:00", "15:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "Inherit the Viper",
        hall: "Hall A",
        time: ["18:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "The Murder of Nicole Brown Simpson",
        hall: "Hall B",
        time: ["18:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "Bad Boys for Life",
        hall: "Hall C",
        time: ["18:00:00", "21:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "Dolittle",
        hall: "Hall D",
        time: ["18:00:00", "21:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "A Fall from Grace",
        hall: "Hall A",
        time: ["21:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "The Sonata",
        hall: "Hall B",
        time: ["21:00:00"],
        language: "English",
      },
    ],
  },
  {
    theaterName: "Major Cineplex Sukhumvit",
    location: {
      address: "1221 Sukhumvit Rd, Phra Khanong",
      city: "Bangkok",
      country: "Thailand",
      zipcode: "10110",
    },
    movieTitle: [
      "The Grudge",
      "Underwater",
      "The Gentlemen",
      "Three Christs",
      "Inherit the Viper",
      "The Murder of Nicole Brown Simpson",
      "Bad Boys for Life",
      "Dolittle",
      "A Fall from Grace",
      "The Sonata",
    ],
    movies: [
      {
        movieTitle: "The Grudge",
        hall: "Hall A",
        time: ["12:00:00", "15:00:00"],
        language: "English",
      },
      {
        movieTitle: "Underwater",
        hall: "Hall B",
        time: ["12:00:00", "15:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "The Gentlemen",
        hall: "Hall C",
        time: ["12:00:00", "15:00:00"],
        language: "English",
      },
      {
        movieTitle: "Three Christs",
        hall: "Hall D",
        time: ["12:00:00", "15:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "Inherit the Viper",
        hall: "Hall A",
        time: ["18:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "The Murder of Nicole Brown Simpson",
        hall: "Hall B",
        time: ["18:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "Bad Boys for Life",
        hall: "Hall C",
        time: ["18:00:00", "21:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "Dolittle",
        hall: "Hall D",
        time: ["18:00:00", "21:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "A Fall from Grace",
        hall: "Hall A",
        time: ["21:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "The Sonata",
        hall: "Hall B",
        time: ["21:00:00"],
        language: "English",
      },
    ],
  },
  {
    theaterName: "Major Cineplex Central World",
    location: {
      address: "4, 4/1-4/2 Rajadamri Rd, Pathum Wan",
      city: "Bangkok",
      country: "Thailand",
      zipcode: "10330",
    },
    movieTitle: [
      "The Grudge",
      "Underwater",
      "Like a Boss",
      "Three Christs",
      "The Gentlemen",
      "The Murder of Nicole Brown Simpson",
      "Bad Boys for Life",
      "Dolittle",
      "A Fall from Grace",
      "The Turning",
    ],
    movies: [
      {
        movieTitle: "The Grudge",
        hall: "Hall A",
        time: ["12:00:00", "15:00:00"],
        language: "English",
      },
      {
        movieTitle: "Underwater",
        hall: "Hall B",
        time: ["12:00:00", "15:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "Like a Boss",
        hall: "Hall C",
        time: ["12:00:00", "15:00:00"],
        language: "English",
      },
      {
        movieTitle: "Three Christs",
        hall: "Hall D",
        time: ["12:00:00", "15:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "The Gentlemen",
        hall: "Hall A",
        time: ["18:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "The Murder of Nicole Brown Simpson",
        hall: "Hall B",
        time: ["18:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "Bad Boys for Life",
        hall: "Hall C",
        time: ["18:00:00", "21:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "Dolittle",
        hall: "Hall D",
        time: ["18:00:00", "21:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "A Fall from Grace",
        hall: "Hall A",
        time: ["21:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "The Turning",
        hall: "Hall B",
        time: ["21:00:00"],
        language: "English",
      },
    ],
  },
  {
    theaterName: "Major Cineplex Pinklao",
    location: {
      address: "7/222 Borommaratchachonnani Rd, Arun Amarin",
      city: "Bangkok",
      country: "Thailand",
      zipcode: "10700",
    },
    movieTitle: [
      "The Turning",
      "Underwater",
      "Like a Boss",
      "Three Christs",
      "Inherit the Viper",
      "The Murder of Nicole Brown Simpson",
      "Bad Boys for Life",
      "Dolittle",
      "A Fall from Grace",
      "The Sonata",
    ],
    movies: [
      {
        movieTitle: "The Turning",
        hall: "Hall A",
        time: ["12:00:00", "15:00:00"],
        language: "English",
      },
      {
        movieTitle: "Underwater",
        hall: "Hall B",
        time: ["12:00:00", "15:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "Like a Boss",
        hall: "Hall C",
        time: ["12:00:00", "15:00:00"],
        language: "English",
      },
      {
        movieTitle: "Three Christs",
        hall: "Hall D",
        time: ["12:00:00", "15:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "Inherit the Viper",
        hall: "Hall A",
        time: ["18:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "The Murder of Nicole Brown Simpson",
        hall: "Hall B",
        time: ["18:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "Bad Boys for Life",
        hall: "Hall C",
        time: ["18:00:00", "21:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "Dolittle",
        hall: "Hall D",
        time: ["18:00:00", "21:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "A Fall from Grace",
        hall: "Hall A",
        time: ["21:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "The Sonata",
        hall: "Hall B",
        time: ["21:00:00"],
        language: "English",
      },
    ],
  },
  {
    theaterName: "Major Cineplex Esplanade Ratchadapisek",
    location: {
      address: "99 Ratchadaphisek Rd, Din Daeng",
      city: "Bangkok",
      country: "Thailand",
      zipcode: "10400",
    },
    movieTitle: [
      "The Grudge",
      "Underwater",
      "Like a Boss",
      "Three Christs",
      "Inherit the Viper",
      "The Murder of Nicole Brown Simpson",
      "The Turning",
      "Dolittle",
      "A Fall from Grace",
      "The Sonata",
    ],
    movies: [
      {
        movieTitle: "The Grudge",
        hall: "Hall A",
        time: ["12:00:00", "15:00:00"],
        language: "English",
      },
      {
        movieTitle: "Underwater",
        hall: "Hall B",
        time: ["12:00:00", "15:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "Like a Boss",
        hall: "Hall C",
        time: ["12:00:00", "15:00:00"],
        language: "English",
      },
      {
        movieTitle: "Three Christs",
        hall: "Hall D",
        time: ["12:00:00", "15:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "Inherit the Viper",
        hall: "Hall A",
        time: ["18:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "The Murder of Nicole Brown Simpson",
        hall: "Hall B",
        time: ["18:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "The Turning",
        hall: "Hall C",
        time: ["18:00:00", "21:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "Dolittle",
        hall: "Hall D",
        time: ["18:00:00", "21:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "A Fall from Grace",
        hall: "Hall A",
        time: ["21:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "The Sonata",
        hall: "Hall B",
        time: ["21:00:00"],
        language: "English",
      },
    ],
  },
  {
    theaterName: "Major Cineplex Mega Bangna",
    location: {
      address: "39 Moo 6 Bang Na-Trat Frontage Rd, Bang Kaeo",
      city: "Samut Prakan",
      country: "Thailand",
      zipcode: "10540",
    },
    movieTitle: [
      "The Grudge",
      "The Last Full Measure",
      "Three Christs",
      "Inherit the Viper",
      "Bad Boys for Life",
      "Dolittle",
      "A Fall from Grace",
      "The Sonata",
    ],
    movies: [
      {
        movieTitle: "The Grudge",
        hall: "Hall A",
        time: ["12:00:00", "15:00:00"],
        language: "English",
      },
      {
        movieTitle: "The Last Full Measure",
        hall: "Hall B",
        time: ["12:00:00", "15:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "The Grudge",
        hall: "Hall C",
        time: ["12:00:00", "15:00:00"],
        language: "English",
      },
      {
        movieTitle: "Three Christs",
        hall: "Hall D",
        time: ["12:00:00", "15:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "Inherit the Viper",
        hall: "Hall A",
        time: ["18:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "The Murder of Nicole Brown Simpson",
        hall: "Hall B",
        time: ["18:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "Bad Boys for Life",
        hall: "Hall C",
        time: ["18:00:00", "21:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "Dolittle",
        hall: "Hall D",
        time: ["18:00:00", "21:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "A Fall from Grace",
        hall: "Hall A",
        time: ["21:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "The Sonata",
        hall: "Hall B",
        time: ["21:00:00"],
        language: "English",
      },
    ],
  },
  {
    theaterName: "Major Cineplex Central WestGate",
    location: {
      address: "199, 199/1-2 Moo 6, Sao Thong Hin",
      city: "Nonthaburi",
      country: "Thailand",
      zipcode: "11140",
    },
    movieTitle: [
      "The Grudge",
      "Underwater",
      "Like a Boss",
      "Three Christs",
      "The Last Full Measure",
      "The Murder of Nicole Brown Simpson",
      "Bad Boys for Life",
      "Dolittle",
      "A Fall from Grace",
      "The Sonata",
    ],
    movies: [
      {
        movieTitle: "The Grudge",
        hall: "Hall A",
        time: ["12:00:00", "15:00:00"],
        language: "English",
      },
      {
        movieTitle: "Underwater",
        hall: "Hall B",
        time: ["12:00:00", "15:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "Like a Boss",
        hall: "Hall C",
        time: ["12:00:00", "15:00:00"],
        language: "English",
      },
      {
        movieTitle: "Three Christs",
        hall: "Hall D",
        time: ["12:00:00", "15:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "The Last Full Measure",
        hall: "Hall A",
        time: ["18:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "The Murder of Nicole Brown Simpson",
        hall: "Hall B",
        time: ["18:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "Bad Boys for Life",
        hall: "Hall C",
        time: ["18:00:00", "21:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "Dolittle",
        hall: "Hall D",
        time: ["18:00:00", "21:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "A Fall from Grace",
        hall: "Hall A",
        time: ["21:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "The Sonata",
        hall: "Hall B",
        time: ["21:00:00"],
        language: "English",
      },
    ],
  },
  {
    theaterName: "Major Cineplex Chiang Mai",
    location: {
      address: "4th Floor, Central Plaza Chiang Mai Airport, 2 Mahidol Rd",
      city: "Chiang Mai",
      country: "Thailand",
      zipcode: "50100",
    },
    movieTitle: [
      "The Last Full Measure",
      "Underwater",
      "Like a Boss",
      "Three Christs",
      "Inherit the Viper",
      "The Murder of Nicole Brown Simpson",
      "Bad Boys for Life",
      "Dolittle",
      "A Fall from Grace",
      "The Sonata",
    ],
    movies: [
      {
        movieTitle: "The Last Full Measure",
        hall: "Hall A",
        time: ["12:00:00", "15:00:00"],
        language: "English",
      },
      {
        movieTitle: "Underwater",
        hall: "Hall B",
        time: ["12:00:00", "15:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "Like a Boss",
        hall: "Hall C",
        time: ["12:00:00", "15:00:00"],
        language: "English",
      },
      {
        movieTitle: "Three Christs",
        hall: "Hall D",
        time: ["12:00:00", "15:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "Inherit the Viper",
        hall: "Hall A",
        time: ["18:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "The Murder of Nicole Brown Simpson",
        hall: "Hall B",
        time: ["18:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "Bad Boys for Life",
        hall: "Hall C",
        time: ["18:00:00", "21:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "Dolittle",
        hall: "Hall D",
        time: ["18:00:00", "21:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "A Fall from Grace",
        hall: "Hall A",
        time: ["21:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "The Sonata",
        hall: "Hall B",
        time: ["21:00:00"],
        language: "English",
      },
    ],
  },
  {
    theaterName: "Major Cineplex Pattaya",
    location: {
      address: "333/102 Moo 9, Pattaya Klang Rd, Nong Prue",
      city: "Chonburi",
      country: "Thailand",
      zipcode: "20150",
    },
    movieTitle: [
      "The Grudge",
      "John Henry",
      "Like a Boss",
      "Three Christs",
      "Inherit the Viper",
      "The Murder of Nicole Brown Simpson",
      "Bad Boys for Life",
      "Dolittle",
      "A Fall from Grace",
      "The Sonata",
    ],
    movies: [
      {
        movieTitle: "The Grudge",
        hall: "Hall A",
        time: ["12:00:00", "15:00:00"],
        language: "English",
      },
      {
        movieTitle: "John Henry",
        hall: "Hall B",
        time: ["12:00:00", "15:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "Like a Boss",
        hall: "Hall C",
        time: ["12:00:00", "15:00:00"],
        language: "English",
      },
      {
        movieTitle: "Three Christs",
        hall: "Hall D",
        time: ["12:00:00", "15:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "Inherit the Viper",
        hall: "Hall A",
        time: ["18:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "The Murder of Nicole Brown Simpson",
        hall: "Hall B",
        time: ["18:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "Bad Boys for Life",
        hall: "Hall C",
        time: ["18:00:00", "21:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "Dolittle",
        hall: "Hall D",
        time: ["18:00:00", "21:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "A Fall from Grace",
        hall: "Hall A",
        time: ["21:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "The Sonata",
        hall: "Hall B",
        time: ["21:00:00"],
        language: "English",
      },
    ],
  },
  {
    theaterName: "Major Cineplex Central Korat",
    location: {
      address: "990 Mittraphap Rd, Nai Mueang",
      city: "Nakhon Ratchasima",
      country: "Thailand",
      zipcode: "30000",
    },
    movieTitle: [
      "The Grudge",
      "Underwater",
      "John Henry",
      "The Rhythm Section",
      "Inherit the Viper",
      "The Murder of Nicole Brown Simpson",
      "Bad Boys for Life",
      "Dolittle",
      "A Fall from Grace",
      "The Sonata",
    ],
    movies: [
      {
        movieTitle: "The Grudge",
        hall: "Hall A",
        time: ["12:00:00", "15:00:00"],
        language: "English",
      },
      {
        movieTitle: "Underwater",
        hall: "Hall B",
        time: ["12:00:00", "15:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "John Henry",
        hall: "Hall C",
        time: ["12:00:00", "15:00:00"],
        language: "English",
      },
      {
        movieTitle: "The Rhythm Section",
        hall: "Hall D",
        time: ["12:00:00", "15:00:00"],
        language: "English",
      },
      {
        movieTitle: "Inherit the Viper",
        hall: "Hall A",
        time: ["18:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "The Murder of Nicole Brown Simpson",
        hall: "Hall B",
        time: ["18:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "Bad Boys for Life",
        hall: "Hall C",
        time: ["18:00:00", "21:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "Dolittle",
        hall: "Hall D",
        time: ["18:00:00", "21:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "A Fall from Grace",
        hall: "Hall A",
        time: ["21:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "The Sonata",
        hall: "Hall B",
        time: ["21:00:00"],
        language: "English",
      },
    ],
  },
  {
    theaterName: "Major Cineplex Hatyai",
    location: {
      address: "5th Floor, Central Festival Hatyai, 1518 Kanchanavanich Rd",
      city: "Songkhla",
      country: "Thailand",
      zipcode: "90110",
    },
    movieTitle: [
      "The Grudge",
      "Underwater",
      "Like a Boss",
      "Three Christs",
      "Inherit the Viper",
      "The Murder of Nicole Brown Simpson",
      "Bad Boys for Life",
      "Dolittle",
      "A Fall from Grace",
      "The Sonata",
    ],
    movies: [
      {
        movieTitle: "The Grudge",
        hall: "Hall A",
        time: ["12:00:00", "15:00:00"],
        language: "English",
      },
      {
        movieTitle: "Underwater",
        hall: "Hall B",
        time: ["12:00:00", "15:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "Like a Boss",
        hall: "Hall C",
        time: ["12:00:00", "15:00:00"],
        language: "English",
      },
      {
        movieTitle: "Three Christs",
        hall: "Hall D",
        time: ["12:00:00", "15:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "Inherit the Viper",
        hall: "Hall A",
        time: ["18:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "The Murder of Nicole Brown Simpson",
        hall: "Hall B",
        time: ["18:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "Bad Boys for Life",
        hall: "Hall C",
        time: ["18:00:00", "21:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "Dolittle",
        hall: "Hall D",
        time: ["18:00:00", "21:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "A Fall from Grace",
        hall: "Hall A",
        time: ["21:00:00"],
        language: "Thai",
      },
      {
        movieTitle: "The Sonata",
        hall: "Hall B",
        time: ["21:00:00"],
        language: "English",
      },
    ],
  },
];

const hallsData = [
  {
    theaterName: "Major Cineplex Ratchayothin",
    hallName: "Hall A",
    seatingPlan: { rows: 10, seatsPerRow: 15 },
    seatPrice: 200,
    projection: "IMAX LAZER 2D",
  },
  {
    theaterName: "Major Cineplex Ratchayothin",
    hallName: "Hall B",
    seatingPlan: { rows: 15, seatsPerRow: 20 },
    seatPrice: 200,
    projection: "2D",
  },
  {
    theaterName: "Major Cineplex Ratchayothin",
    hallName: "Hall C",
    seatingPlan: { rows: 12, seatsPerRow: 15 },
    seatPrice: 200,
    projection: "LAZER CINIMA",
  },
  {
    theaterName: "Major Cineplex Ratchayothin",
    hallName: "Hall D",
    seatingPlan: { rows: 10, seatsPerRow: 15 },
    seatPrice: 200,
    projection: "IMAX LAZER 3D",
  },
  {
    theaterName: "Major Cineplex Sukhumvit",
    hallName: "Hall A",
    seatingPlan: { rows: 10, seatsPerRow: 15 },
    seatPrice: 200,
    projection: "IMAX LAZER 2D",
  },
  {
    theaterName: "Major Cineplex Sukhumvit",
    hallName: "Hall B",
    seatingPlan: { rows: 10, seatsPerRow: 15 },
    seatPrice: 200,
    projection: "IMAX LAZER 2D",
  },
  {
    theaterName: "Major Cineplex Sukhumvit",
    hallName: "Hall C",
    seatingPlan: { rows: 12, seatsPerRow: 15 },
    seatPrice: 200,
    projection: "LAZER CINIMA",
  },
  {
    theaterName: "Major Cineplex Sukhumvit",
    hallName: "Hall D",
    seatingPlan: { rows: 10, seatsPerRow: 15 },
    seatPrice: 200,
    projection: "IMAX LAZER 3D",
  },
  {
    theaterName: "Major Cineplex Central World",
    hallName: "Hall A",
    seatingPlan: { rows: 10, seatsPerRow: 15 },
    seatPrice: 200,
    projection: "IMAX LAZER 2D",
  },
  {
    theaterName: "Major Cineplex Central World",
    hallName: "Hall B",
    seatingPlan: { rows: 10, seatsPerRow: 15 },
    seatPrice: 200,
    projection: "2D",
  },
  {
    theaterName: "Major Cineplex Central World",
    hallName: "Hall B",
    seatingPlan: { rows: 10, seatsPerRow: 15 },
    seatPrice: 200,
    projection: "2D",
  },
  {
    theaterName: "Major Cineplex Central World",
    hallName: "Hall D",
    seatingPlan: { rows: 10, seatsPerRow: 15 },
    seatPrice: 200,
    projection: "IMAX LAZER 3D",
  },
  {
    theaterName: "Major Cineplex Pinklao",
    hallName: "Hall A",
    seatingPlan: { rows: 10, seatsPerRow: 15 },
    seatPrice: 200,
    projection: "IMAX LAZER 2D",
  },
  {
    theaterName: "Major Cineplex Pinklao",
    hallName: "Hall B",
    seatingPlan: { rows: 15, seatsPerRow: 20 },
    seatPrice: 200,
    projection: "2D",
  },
  {
    theaterName: "Major Cineplex Pinklao",
    hallName: "Hall C",
    seatingPlan: { rows: 12, seatsPerRow: 15 },
    seatPrice: 200,
    projection: "LAZER CINIMA",
  },
  {
    theaterName: "Major Cineplex Pinklao",
    hallName: "Hall D",
    seatingPlan: { rows: 12, seatsPerRow: 15 },
    seatPrice: 200,
    projection: "LAZER CINIMA",
  },
  {
    theaterName: "Major Cineplex Esplanade Ratchadapisek",
    hallName: "Hall A",
    seatingPlan: { rows: 10, seatsPerRow: 15 },
    seatPrice: 200,
    projection: "IMAX LAZER 2D",
  },
  {
    theaterName: "Major Cineplex Esplanade Ratchadapisek",
    hallName: "Hall B",
    seatingPlan: { rows: 12, seatsPerRow: 15 },
    seatPrice: 200,
    projection: "LAZER CINIMA",
  },
  {
    theaterName: "Major Cineplex Esplanade Ratchadapisek",
    hallName: "Hall C",
    seatingPlan: { rows: 12, seatsPerRow: 15 },
    seatPrice: 200,
    projection: "LAZER CINIMA",
  },
  {
    theaterName: "Major Cineplex Esplanade Ratchadapisek",
    hallName: "Hall D",
    seatingPlan: { rows: 12, seatsPerRow: 15 },
    seatPrice: 200,
    projection: "LAZER CINIMA",
  },
  {
    theaterName: "Major Cineplex Central WestGate",
    hallName: "Hall A",
    seatingPlan: { rows: 10, seatsPerRow: 15 },
    seatPrice: 200,
    projection: "IMAX LAZER 2D",
  },
  {
    theaterName: "Major Cineplex Central WestGate",
    hallName: "Hall B",
    seatingPlan: { rows: 15, seatsPerRow: 20 },
    seatPrice: 200,
    projection: "2D",
  },
  {
    theaterName: "Major Cineplex Central WestGate",
    hallName: "Hall C",
    seatingPlan: { rows: 12, seatsPerRow: 15 },
    seatPrice: 200,
    projection: "LAZER CINIMA",
  },
  {
    theaterName: "Major Cineplex Central WestGate",
    hallName: "Hall D",
    seatingPlan: { rows: 10, seatsPerRow: 15 },
    seatPrice: 200,
    projection: "IMAX LAZER 3D",
  },
  {
    theaterName: "Major Cineplex Chiang Mai",
    hallName: "Hall A",
    seatingPlan: { rows: 10, seatsPerRow: 15 },
    seatPrice: 200,
    projection: "IMAX LAZER 2D",
  },
  {
    theaterName: "Major Cineplex Chiang Mai",
    hallName: "Hall B",
    seatingPlan: { rows: 10, seatsPerRow: 15 },
    seatPrice: 200,
    projection: "2D",
  },
  {
    theaterName: "Major Cineplex Chiang Mai",
    hallName: "Hall C",
    seatingPlan: { rows: 10, seatsPerRow: 15 },
    seatPrice: 200,
    projection: "LAZER CINIMA",
  },
  {
    theaterName: "Major Cineplex Chiang Mai",
    hallName: "Hall D",
    seatingPlan: { rows: 10, seatsPerRow: 15 },
    seatPrice: 200,
    projection: "IMAX LAZER 3D",
  },
  {
    theaterName: "Major Cineplex Pattaya",
    hallName: "Hall A",
    seatingPlan: { rows: 15, seatsPerRow: 20 },
    seatPrice: 200,
    projection: "2D",
  },
  {
    theaterName: "Major Cineplex Pattaya",
    hallName: "Hall B",
    seatingPlan: { rows: 15, seatsPerRow: 20 },
    seatPrice: 200,
    projection: "2D",
  },
  {
    theaterName: "Major Cineplex Pattaya",
    hallName: "Hall C",
    seatingPlan: { rows: 12, seatsPerRow: 15 },
    seatPrice: 200,
    projection: "LAZER CINIMA",
  },
  {
    theaterName: "Major Cineplex Pattaya",
    hallName: "Hall D",
    seatingPlan: { rows: 10, seatsPerRow: 15 },
    seatPrice: 200,
    projection: "IMAX LAZER 3D",
  },
  {
    theaterName: "Major Cineplex Central Korat",
    hallName: "Hall A",
    seatingPlan: { rows: 10, seatsPerRow: 15 },
    seatPrice: 200,
    projection: "IMAX LAZER 2D",
  },
  {
    theaterName: "Major Cineplex Central Korat",
    hallName: "Hall B",
    seatingPlan: { rows: 15, seatsPerRow: 20 },
    seatPrice: 200,
    projection: "2D",
  },
  {
    theaterName: "Major Cineplex Central Korat",
    hallName: "Hall C",
    seatingPlan: { rows: 12, seatsPerRow: 15 },
    seatPrice: 200,
    projection: "LAZER CINIMA",
  },
  {
    theaterName: "Major Cineplex Central Korat",
    hallName: "Hall D",
    seatingPlan: { rows: 10, seatsPerRow: 15 },
    seatPrice: 200,
    projection: "IMAX LAZER 3D",
  },
  {
    theaterName: "Major Cineplex Hatyai",
    hallName: "Hall A",
    seatingPlan: { rows: 10, seatsPerRow: 15 },
    seatPrice: 200,
    projection: "IMAX LAZER 2D",
  },
  {
    theaterName: "Major Cineplex Hatyai",
    hallName: "Hall B",
    seatingPlan: { rows: 15, seatsPerRow: 20 },
    seatPrice: 200,
    projection: "2D",
  },
  {
    theaterName: "Major Cineplex Hatyai",
    hallName: "Hall C",
    seatingPlan: { rows: 12, seatsPerRow: 15 },
    seatPrice: 200,
    projection: "LAZER CINIMA",
  },
  {
    theaterName: "Major Cineplex Hatyai",
    hallName: "Hall D",
    seatingPlan: { rows: 12, seatsPerRow: 15 },
    seatPrice: 200,
    projection: "LAZER CINIMA",
  },
];

const bookingsData = [
  {
    movieTitle: "The Grudge",
    theaterName: "Major Cineplex Ratchayothin",
    showtime: "2024-12-15T05:00:00Z",
    hall: "Hall A",
    status: true,
    totalPrice: 800,
    bookedSeats: ["A1", "A2", "B1", "B2"],
  },
  {
    movieTitle: "Underwater",
    theaterName: "Major Cineplex Sukhumvit",
    showtime: "2024-12-15T08:30:00Z",
    hall: "Hall B",
    status: true,
    totalPrice: 800,
    bookedSeats: ["B1", "B2", "C1", "C2"],
  },
  {
    movieTitle: "Like a Boss",
    theaterName: "Major Cineplex Central World",
    showtime: "2024-12-15T08:00:00Z",
    hall: "Hall C",
    status: true,
    totalPrice: 1000,
    bookedSeats: ["C1", "C2", "D1", "D2", "E1"],
  },
  {
    movieTitle: "Three Christs",
    theaterName: "Major Cineplex Pinklao",
    showtime: "2024-12-15T08:00:00Z",
    hall: "Hall D",
    status: true,
    totalPrice: 800,
    bookedSeats: ["D1", "D2", "E1", "E2"],
  },
  {
    movieTitle: "The Grudge",
    theaterName: "Major Cineplex Esplanade Ratchadapisek",
    showtime: "2024-12-15T05:00:00Z",
    hall: "Hall A",
    status: true,
    totalPrice: 800,
    bookedSeats: ["A1", "A2", "A3", "B1"],
  },
  {
    movieTitle: "Underwater",
    theaterName: "Major Cineplex Central WestGate",
    showtime: "2024-12-15T05:00:00Z",
    hall: "Hall B",
    status: true,
    totalPrice: 1000,
    bookedSeats: ["B1", "B2", "B3", "C1", "C2"],
  },
  {
    movieTitle: "Like a Boss",
    theaterName: "Major Cineplex Chiang Mai",
    showtime: "2024-12-15T05:00:00Z",
    hall: "Hall C",
    status: true,
    totalPrice: 1200,
    bookedSeats: ["C1", "C2", "D1", "D2", "E1", "E2"],
  },
  {
    movieTitle: "Inherit the Viper",
    theaterName: "Major Cineplex Pattaya",
    showtime: "2024-12-15T11:00:00Z",
    hall: "Hall A",
    status: true,
    totalPrice: 800,
    bookedSeats: ["C1", "C2", "D1", "D2"],
  },
  {
    movieTitle: "The Rhythm Section",
    theaterName: "Major Cineplex Central Korat",
    showtime: "2024-12-15T05:00:00Z",
    hall: "Hall D",
    status: true,
    totalPrice: 1000,
    bookedSeats: ["A1", "A2", "A3", "A4", "A5"],
  },
  {
    movieTitle: "Shazam! Fury of the Gods",
    theaterName: "Major Cineplex Hatyai",
    showtime: "2024-12-15T20:00:00Z",
    hall: "Hall A",
    status: true,
    totalPrice: 1000,
    bookedSeats: ["A1", "A2", "B1", "B2", "C1"],
  },
  {
    movieTitle: "Like a Boss",
    theaterName: "Major Cineplex Ratchayothin",
    showtime: "2024-12-15T08:00:00Z",
    hall: "Hall C",
    status: true,
    totalPrice: 1000,
    bookedSeats: ["C1", "C2", "C3", "D1", "D2"],
  },
  {
    movieTitle: "Underwater",
    theaterName: "Major Cineplex Sukhumvit",
    showtime: "2024-12-16T05:00:00Z",
    hall: "Hall B",
    status: true,
    totalPrice: 800,
    bookedSeats: ["B1", "B2", "C1", "D1"],
  },
  {
    movieTitle: "The Grudge",
    theaterName: "Major Cineplex Central World",
    showtime: "2024-12-16T05:00:00Z",
    hall: "Hall A",
    status: true,
    totalPrice: 1000,
    bookedSeats: ["A1", "A2", "B1", "B2", "C1"],
  },
  {
    movieTitle: "Like a Boss",
    theaterName: "Major Cineplex Pinklao",
    showtime: "2024-12-16T05:00:00Z",
    hall: "Hall C",
    status: true,
    totalPrice: 800,
    bookedSeats: ["C1", "D1", "E1", "F1"],
  },
  {
    movieTitle: "The Grudge",
    theaterName: "Major Cineplex Esplanade Ratchadapisek",
    showtime: "2024-12-16T05:00:00Z",
    hall: "Hall A",
    status: true,
    totalPrice: 800,
    bookedSeats: ["A5", "B2", "B3", "C1"],
  },
  {
    movieTitle: "Three Christs",
    theaterName: "Major Cineplex Central WestGate",
    showtime: "2024-12-16T05:00:00Z",
    hall: "Hall D",
    status: true,
    totalPrice: 800,
    bookedSeats: ["D1", "D2", "E1", "F1"],
  },
  {
    movieTitle: "Underwater",
    theaterName: "Major Cineplex Chiang Mai",
    showtime: "2024-12-16T05:00:00Z",
    hall: "Hall B",
    status: true,
    totalPrice: 800,
    bookedSeats: ["B1", "B2", "C1", "C2"],
  },
  {
    movieTitle: "Inherit the Viper",
    theaterName: "Major Cineplex Pattaya",
    showtime: "2024-12-16T11:00:00Z",
    hall: "Hall A",
    status: true,
    totalPrice: 800,
    bookedSeats: ["A1", "A2", "B1", "B2"],
  },
  {
    movieTitle: "The Rhythm Section",
    theaterName: "Major Cineplex Central Korat",
    showtime: "2024-12-16T05:00:00Z",
    hall: "Hall D",
    status: true,
    totalPrice: 1000,
    bookedSeats: ["D1", "D2", "E1", "E2", "F1"],
  },
];

// Function to import data
async function importData() {
  try {
    // Import Movies
    for (const movie of moviesData) {
      const startDateTime = new Date(movie.startDate);
      const endDateTime = new Date(movie.endDate);
      movie.startDate = Timestamp.fromDate(startDateTime);
      movie.endDate = Timestamp.fromDate(endDateTime);

      await db.collection("movies").add(movie);
      console.log(`Movie ${movie.title} added.`);
    }

    // Import Theaters
    for (const theater of theatersData) {
      await db.collection("theaters").add(theater);
      console.log(`Theater ${theater.theaterName} added.`);
    }

    // Import Halls
    for (const hall of hallsData) {
      await db.collection("halls").add(hall);
      console.log(`Hall ${hall.hallName} in ${hall.theaterName} added.`);
    }

    for (const booking of bookingsData) {
      // Convert showtime string to Firestore Timestamp
      const showtimeDate = new Date(booking.showtime);
      booking.showtime = Timestamp.fromDate(showtimeDate);

      await db.collection("bookings").add(booking);
      console.log(
        `Booking for ${booking.movieTitle} in ${booking.theaterName} added.`
      );
    }

    console.log("Data import completed successfully.");
  } catch (error) {
    console.error("Error importing data:", error);
  }
}

importData();
